#!/usr/bin/python3

import sys
import time
import datetime
import socket
import board
import digitalio
import adafruit_character_lcd.character_lcd as character_lcd

lcd_columns = 16
lcd_rows = 2
lcd_rs = digitalio.DigitalInOut(board.D22)
lcd_en = digitalio.DigitalInOut(board.D17)
lcd_d7 = digitalio.DigitalInOut(board.D18)
lcd_d6 = digitalio.DigitalInOut(board.D23)
lcd_d5 = digitalio.DigitalInOut(board.D24)
lcd_d4 = digitalio.DigitalInOut(board.D25)

lcd = character_lcd.Character_LCD_Mono(lcd_rs, lcd_en, lcd_d4, lcd_d5, lcd_d6,
                                      lcd_d7, lcd_columns, lcd_rows)

lcd.clear()
horaire = datetime.datetime.now().strftime('%d %b %H:%M') 

if  sys.argv[1] != '':
	lcd.message = str(horaire) + '\n' + sys.argv[2]
else:
	lcd.message = str(horaire)
